#!/usr/bin/env python3
"""
SPI Flash 图片批烧录 — 生成固件内的 C 代码

用法: python make_flash_batch.py <图片目录> <起始编号> <数量>
示例: python make_flash_batch.py Core/Src/generated/images 0 5   # 前5张

生成 flash_batch.c — 包含指定图片的 C 数组引用和烧录循环
每次取 N 张图片, 编译进固件, F5 烧录, MCU 写入 SPI Flash。
"""

import sys, os, re, glob

def main():
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)

    img_dir = sys.argv[1]
    start = int(sys.argv[2])
    count = int(sys.argv[3])

    files = sorted(glob.glob(os.path.join(img_dir, "*.c")))

    batch = files[start:start+count]
    if not batch:
        print(f"No files at index {start}")
        sys.exit(1)

    print(f"Batch: files {start}-{start+len(batch)-1} of {len(files)}")
    print()

    includes = []
    entries = []

    offset = 0  # simplified; real offsets from make_spiflash_bin.py

    for f_path in batch:
        # find descriptor name
        with open(f_path, encoding='utf-8', errors='ignore') as f:
            content = f.read()
        m = re.search(r'const lv_image_dsc_t (\w+) =', content)
        if not m:
            m = re.search(r'const.* (\w+_map)\[', content)
            if m:
                desc_name = m.group(1)  # use _map var name
            else:
                continue
        else:
            desc_name = m.group(1)

        includes.append(f'extern const lv_image_dsc_t {desc_name};')
        entries.append((desc_name, os.path.basename(f_path)))

    # Generate .c file content
    print("// auto-generated by make_flash_batch.py")
    print('// Copy this into main.c USER CODE 2 (replace flash loop)\n')
    print('#include "en25q128.h"\n')
    for inc in includes:
        print(inc)

    print('\nstatic const struct {')
    print('    const uint8_t *data;')
    print('    uint32_t size;')
    print('    uint32_t offset;')
    print('    const char *name;')
    print('} batch_table[] = {')

    for desc_name, fname in entries:
        print(f'    {{(const uint8_t*){desc_name}.data, {desc_name}.data_size, 0, "{fname}"}}, /* TODO: offset */')

    print('    {NULL, 0, 0, NULL}')
    print('};\n')

    print('// --- Flash write loop ---')
    print('printf("Writing %d images to SPI Flash...\\r\\n", (int)(sizeof(batch_table)/sizeof(batch_table[0])-1));')
    print('for (int i = 0; batch_table[i].data; i++) {')
    print('    printf("  [%d] %%s (%%lu B)\\r\\n", i, batch_table[i].name, batch_table[i].size);')
    print('    EN25Q128_Write(batch_table[i].data, batch_table[i].offset, batch_table[i].size);')
    print('}')
    print('printf("DONE\\r\\n");')
    print('while(1);')

if __name__ == '__main__':
    main()
