#!/usr/bin/env python3
"""
gen_lfs_batch.py — 将 lfs_img.bin 拆分为 batch_XX.h 头文件

用法:
  python scripts/gen_lfs_batch.py

输出:
  scripts/batch_00.h  ~  batch_NN.h  每个包含一段 SPI Flash 数据
  供 flash_new_batches.bat + main_batch.c 烧录使用

块大小: 512KB/块 (安全值, 适应 1MB 内部 Flash 限制)
"""

import os, math

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BIN_PATH   = os.path.join(SCRIPT_DIR, "lfs_img.bin")
OUT_DIR    = SCRIPT_DIR

CHUNK_SIZE = 512 * 1024  # 512KB

def gen_batch(data: bytes, offset: int, index: int) -> str:
    """生成一个 batch 头文件的文本"""
    size = len(data)
    lines = []
    lines.append(f"// Auto-generated by gen_lfs_batch.py")
    lines.append(f"// Batch {index}: {size} bytes, offset 0x{offset:08X}")
    lines.append(f"")
    lines.append(f"static const uint32_t batch_0_offset = 0x{offset:08X}U;")
    lines.append(f"static const uint32_t batch_0_size   = {size}U;")
    lines.append(f"static const uint8_t  batch_0_data[] = {{")

    # 16 bytes per line
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hex_str},")

    lines.append(f"}};")
    return "\n".join(lines)


def main():
    if not os.path.exists(BIN_PATH):
        print(f"[ERR] 找不到 {BIN_PATH}")
        print("请先运行 make_lfs_image.py 生成 lfs_img.bin")
        return False

    total_size = os.path.getsize(BIN_PATH)
    print(f"  lfs_img.bin: {total_size:,} bytes ({total_size/1024/1024:.1f} MB)")
    print(f"  每块: {CHUNK_SIZE:,} bytes ({CHUNK_SIZE/1024:.0f} KB)")

    with open(BIN_PATH, "rb") as f:
        data = f.read()

    num_chunks = math.ceil(total_size / CHUNK_SIZE)
    print(f"  总块数: {num_chunks}")
    print()

    for i in range(num_chunks):
        offset = i * CHUNK_SIZE
        chunk = data[offset : offset + CHUNK_SIZE]
        out_name = f"batch_{i:02d}.h"
        out_path = os.path.join(OUT_DIR, out_name)

        content = gen_batch(chunk, offset, i)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"  {out_name}: offset=0x{offset:08X}, size={len(chunk):,} bytes")

    print(f"\n完成! 共生成 {num_chunks} 个头文件")
    print(f"运行 flash_new_batches.bat 烧录全部批次")
    return True


if __name__ == "__main__":
    main()
